### ISSUE TITLE
[Publicación de historia] Limitación de publicación de historia fotográfica - Fail

### ISSUE THREAD

**Issue by SharonHurtado** [Azuto-S/Calidad-Instagram#37]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Presionar "Tu historia"| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27177.png" alt="" />| Pass |
| 2| Seleccionar como máximo 10 fotos para la publicación| | Fail |

**Comment by SharonHurtado** [comment]
La cantidad de seleccion de fotos es limitada, por lo que limita la publicación de la historia foografica.
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_28035.png)

**Comment by SharonHurtado** [comment]
https://jose27vc.testquality.com defect [D29](https://jose27vc.testquality.com/project/12827/result/2565692/defect/9068).

**Comment by Azuto-S** [comment]
Se ha solucionado el defecto
